### ISSUE TITLE
Atualizar Template de issue para Formato padrão atual do github (YAML)

### ISSUE THREAD

**Issue by ArtyMend07** [SBD1/2025.1-Star_Wars-11#28]
## Tipo de Issue
- [ ] Melhoria
- [x] Bug
- [ ] Nova funcionalidade
- [ ] Tarefa
- [ ] Outro

## Descrição
Necessário atualizar os templates de issues do repositório para o formato YAML moderno do GitHub. O template atual em markdown precisa ser convertido para aproveitar os recursos mais recentes do GitHub, como validações e campos estruturados.

## Solução Proposta
Implementar novo template YAML com a seguinte estrutura:
```yaml
name: 📋 Issue Padrão
description: Template padrão para criação de issues
title: "[Issue]: "
labels: []
body:
  - type: dropdown
    id: tipo
    attributes:
      label: Tipo de Issue
      options:
        - Bug
        - Melhoria
        - Nova funcionalidade
        - Tarefa
        - Outro
```

## Passos para Implementação
1. Criar pasta `.github/ISSUE_TEMPLATE/`
2. Adicionar arquivo `issue_template.yml`
3. Migrar estrutura atual para formato YAML
4. Adicionar validações e campos estruturados
5. Remover template antigo

## Evidências
Template atual está em formato markdown e precisa ser convertido para YAML conforme estrutura acima.

## Comportamento Esperado
- Interface mais amigável para criação de issues
- Campos validados automaticamente
- Dropdowns funcionais
- Melhor organização das informações

## Dependências ou Issues Relacionadas
N/A

## Prioridade
- [x] Alta
- [ ] Média
- [ ] Baixa

## Responsável(s)
@ArtyMend07

## Checklist de Implementação
- [ ] Criar diretório ISSUE_TEMPLATE
- [ ] Implementar template YAML
- [ ] Testar criação de issues
- [ ] Remover template antigo
- [ ] Atualizar documentação
